Document required RBAC permissions
utilitywarehouse/kube-applier pull request #198
Opened 2021-01-13 16:35 UTC by alkar

2021-01-13 16:36 UTC, george-angel approved these changes

2021-01-13 16:37 UTC, george-angel requested changes
Shouldn't this be in kustomize base - and you link to it?

2021-01-13 16:46 UTC, alkar commented
> Shouldn't this be in kustomize base - and you link to it?

This should go in whatever namespace contains cluster resources, essentially the same namespace that imports the CRD base. So I didn't want to create a new base just for this role. I suppose we could bundle it with the CRDs and rename the base to something like "cluster". Thoughts?

2021-01-14 14:59 UTC, alkar commented
Addressed in #201

2021-01-14 14:59 UTC, closed without merging